services:
  # שרת WhatsApp הראשי
  - type: web
    name: whatsapp-bulk-sender
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      # התקנת Node.js dependencies
      npm install
      npm install whatsapp-web.js@1.23.0
      # התקנת Python וחבילותיו
      apt-get install -y python3.10 python3.10-pip
      python3.10 -m pip install --upgrade pip
      python3.10 -m pip install -r requirements.txt
      cd rasa && rasa train && cd ..
    startCommand: |
      # התקנת Python וחבילות נדרשות בזמן ריצה
      apt-get update && apt-get install -y python3.10 python3.10-pip
      python3.10 -m pip install -r requirements.txt
      # הוספת Poetry לPATH
      export PATH="/opt/render/project/poetry/bin:$PATH"
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - services/**
        - routes/**

  # שרת Rasa
  - type: web
    name: rasa-server
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install rasa==3.0.0
      python -m pip install -r rasa/requirements.txt
      cd rasa && rasa train
    startCommand: |
      cd rasa && rasa run --enable-api --cors "*"
    envVars:
      - key: PORT
        value: 5005
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
    buildFilter:
      paths:
        - rasa/**
        - rasa/requirements.txt 