services:
  - type: web
    name: whatsapp-bulk-sender
    env: node
    buildCommand: |
      # התקנת חבילות מערכת
      apt-get update
      apt-get install -y chromium chromium-driver python3-venv

      # יצירת סביבת Python וירטואלית
      python3 -m venv venv
      . venv/bin/activate

      # התקנת pip ו-rasa
      pip install --upgrade pip
      pip install rasa
      pip install -r requirements.txt

      # הגדרת משתני סביבה
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      export PATH=$PATH:/usr/bin/chromium

      # התקנת חבילות npm
      npm install
      npm install puppeteer

      # אימון rasa
      cd rasa && rasa train && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
      - key: PATH
        value: "/usr/bin/chromium:/opt/render/project/src/venv/bin:${PATH}"
      - key: PYTHON_PATH
        value: "/opt/render/project/src/venv/bin/python3"
    buildFilter:
      paths:
        - package.json
        - requirements.txt
        - services/**
        - routes/**
        - rasa/** 