services:
  - type: web
    name: whatsapp-bulk-sender
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      npm install
      python3 -m pip install --upgrade pip
      python3 -m pip install rasa
      python3 -m pip install -r requirements.txt
      cd rasa && rasa train && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium"
    buildFilter:
      paths:
        - package.json
        - requirements.txt
        - services/**
        - routes/**
        - rasa/** 