services:
  - type: web
    name: rasa-server
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y python3.8 python3.8-pip
      python3.8 -m pip install --upgrade pip
      python3.8 -m pip install -r requirements.txt
      rasa train
    startCommand: rasa run --enable-api --cors "*" --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "true"
    buildFilter:
      paths:
        - "**/*.yml"
        - "**/*.yaml"
        - requirements.txt
        - data/**
        - actions/**
        - tests/** 